use std::collections::{HashMap, HashSet};

use crate::inspector::profile::CapabilityProfile;
use crate::legislator::cross_validator::CrossValidationResult;
use crate::legislator::heuristics::Permission;
use crate::legislator::source_bind::WorkloadHashes;
use crate::termutil::{escape_kdl_string, sanitize_for_terminal};
use crate::tool_def::ToolDefinition;
use crate::verifier::manifest::{ManifestFinding, scan_manifest};
use crate::verifier::ris::{RisScore, score_tool};
use crate::verifier::tools_diff::hash_tools_list;

/// Base syscalls that are always allowed (safe for any process).
const BASE_SYSCALLS: &[&str] = &[
    "read",
    "write",
    "openat",
    "close",
    "fstat",
    "mmap",
    "munmap",
    "brk",
    "exit_group",
];

/// Generate a KDL policy draft from cross-validation results and capability profile.
///
/// If `project_hint` is provided, advisory comments are appended based on
/// static analysis of the project's dependencies and source code.
///
/// Live `tools/list` entries drive `args_schema` (W1) and CC / RIS comments (W2).
/// Blocking findings get `deny=#true`. RIS is advisory and never used by `run`.
///
/// `workload` carries the launch-target hashes the draft pins inside the
/// `server` block (`binary-hash` / `entrypoint-hash`, or the reason a target
/// cannot be bound). Pass `&WorkloadHashes::default()` to emit none.
pub fn generate_policy(
    result: &CrossValidationResult,
    capability: &CapabilityProfile,
    project_hint: Option<&crate::legislator::project_hints::ProjectHint>,
    tools: &[ToolDefinition],
    workload: &WorkloadHashes,
) -> String {
    let mut out = String::new();

    out.push_str("// Policy Draft - Auto-generated by MCP Writ\n");
    out.push_str("// REVIEW all entries before deploying\n");
    out.push_str("policy version=2\n");
    out.push('\n');
    out.push_str("// MCP passage rules default fail-closed: resources/prompts/\n");
    out.push_str("// completion/logging methods, server-originated requests, and MRTR\n");
    out.push_str("// `inputRequests` entries pass only with explicit `mcp` allow rules:\n");
    out.push_str("//   server \"<name>\" { mcp { allow \"elicitation/create\" } }\n");
    out.push_str("// tools/list + tools/call stay protocol machinery.\n\n");

    // defaults section
    out.push_str("defaults {\n");

    // filesystem
    build_fs_section(&mut out, result, capability);

    // syscalls
    build_syscalls_section(&mut out, result, capability);

    out.push_str("}\n\n");

    // logging placeholder
    out.push_str("// === Logging ===\n");
    // No logging node needed in KDL minimal policy

    // server with tools
    build_tools_section(&mut out, result, tools, workload);

    // Project hints (advisory)
    if let Some(hint) = project_hint {
        build_project_hints_section(&mut out, hint);
    }

    out
}

/// Build server/tool entries from cross-validation verdicts.
fn args_schema_property(tools: &[ToolDefinition], tool_name: &str) -> String {
    let Some(schema) = tools
        .iter()
        .find(|t| t.name == tool_name)
        .and_then(|t| t.input_schema.as_deref())
    else {
        return String::new();
    };
    format!(" args_schema=\"{}\"", escape_kdl_string(schema))
}

fn findings_by_tool(findings: &[ManifestFinding]) -> HashMap<String, Vec<ManifestFinding>> {
    let mut map: HashMap<String, Vec<ManifestFinding>> = HashMap::new();
    for finding in findings {
        map.entry(finding.tool_name.clone())
            .or_default()
            .push(finding.clone());
    }
    map
}

fn ris_by_tool(tools: &[ToolDefinition]) -> HashMap<String, RisScore> {
    tools
        .iter()
        .map(|t| (t.name.clone(), score_tool(t)))
        .collect()
}

fn tool_has_blocking(map: &HashMap<String, Vec<ManifestFinding>>, name: &str) -> bool {
    map.get(name)
        .map(|fs| fs.iter().any(|f| f.blocking))
        .unwrap_or(false)
}

fn manifest_comment_block(
    name: &str,
    findings_map: &HashMap<String, Vec<ManifestFinding>>,
    ris_map: &HashMap<String, RisScore>,
) -> String {
    let mut s = String::new();
    if let Some(findings) = findings_map.get(name) {
        for f in findings {
            let label = if f.blocking { "REVIEW" } else { "WARNING" };
            s.push_str(&format!(
                "    // {label}: {} ({}) — {}\n",
                f.rule.as_str(),
                f.severity.as_str(),
                sanitize_for_terminal(&f.detail)
            ));
        }
    }
    if let Some(ris) = ris_map.get(name) {
        s.push_str(&format!("    // {}\n", ris.comment()));
    }
    s
}

fn build_tools_section(
    out: &mut String,
    result: &CrossValidationResult,
    discovered: &[ToolDefinition],
    workload: &WorkloadHashes,
) {
    let findings_map = findings_by_tool(&scan_manifest(discovered));
    let ris_map = ris_by_tool(discovered);

    let mut seen_tools: HashSet<String> = HashSet::new();
    let mut tools: Vec<String> = Vec::new();

    let denied: HashSet<String> = result
        .blocked
        .iter()
        .filter_map(|v| v.tool_name.clone())
        .collect();

    let mut warning_notes: HashMap<String, Vec<String>> = HashMap::new();
    for verdict in &result.warnings {
        if let Some(ref tool_name) = verdict.tool_name {
            warning_notes
                .entry(tool_name.clone())
                .or_default()
                .push(verdict.reason.clone());
        }
    }

    fn warning_comment_block(notes: Option<&Vec<String>>) -> String {
        let mut s = String::new();
        if let Some(notes) = notes {
            for reason in notes {
                s.push_str(&format!(
                    "    // WARNING: {}\n",
                    sanitize_for_terminal(reason)
                ));
            }
        }
        s
    }

    // Deny candidates first so a mismatch is not emitted as an allowed tool.
    for verdict in &result.blocked {
        if let Some(ref tool_name) = verdict.tool_name {
            if !seen_tools.insert(tool_name.clone()) {
                continue;
            }
            let comments = manifest_comment_block(tool_name, &findings_map, &ris_map);
            let warnings = warning_comment_block(warning_notes.get(tool_name));
            tools.push(format!(
                "{comments}{warnings}    // REVIEW: {}\n    tool \"{}\" deny=#true{}",
                escape_kdl_string(&verdict.reason),
                escape_kdl_string(tool_name),
                args_schema_property(discovered, tool_name),
            ));
        }
    }

    // Allowed tools (Case A)
    for verdict in &result.allowed {
        if let Some(ref tool_name) = verdict.tool_name {
            if denied.contains(tool_name) {
                continue;
            }
            if !seen_tools.insert(tool_name.clone()) {
                continue;
            }
            let comments = manifest_comment_block(tool_name, &findings_map, &ris_map);
            let warnings = warning_comment_block(warning_notes.get(tool_name));
            if tool_has_blocking(&findings_map, tool_name) {
                tools.push(format!(
                    "{comments}{warnings}    tool \"{}\" deny=#true{}",
                    escape_kdl_string(tool_name),
                    args_schema_property(discovered, tool_name),
                ));
                continue;
            }
            let side_effect = determine_side_effect(result, tool_name);
            let perms: Vec<String> = result
                .allowed
                .iter()
                .filter(|v| v.tool_name.as_deref() == Some(tool_name))
                .map(|v| {
                    format!(
                        "Capability({}) ∩ Intent({}) [Case A]",
                        v.permission, v.permission
                    )
                })
                .collect();

            tools.push(format!(
                "{comments}{warnings}    // Matched: {}\n    tool \"{}\" side_effect=\"{}\"{}",
                perms.join(", "),
                escape_kdl_string(tool_name),
                side_effect,
                args_schema_property(discovered, tool_name),
            ));
        }
    }

    // Warning tools (Case C) that were not already emitted. A Case-C
    // verdict is "unproven", never "safe": emitting the tool bare would
    // let a call succeed without any capability match having been
    // established. Emit it denied with a REVIEW note — the operator
    // unblocks it only after judging the reason.
    for verdict in &result.warnings {
        if let Some(ref tool_name) = verdict.tool_name {
            if denied.contains(tool_name) {
                continue;
            }
            if !seen_tools.insert(tool_name.clone()) {
                continue;
            }
            let comments = manifest_comment_block(tool_name, &findings_map, &ris_map);
            let warnings = warning_comment_block(warning_notes.get(tool_name));
            if tool_has_blocking(&findings_map, tool_name) {
                tools.push(format!(
                    "{comments}{warnings}    tool \"{}\" deny=#true{}",
                    escape_kdl_string(tool_name),
                    args_schema_property(discovered, tool_name),
                ));
                continue;
            }
            tools.push(format!(
                "{comments}{warnings}    // REVIEW: {}\n    tool \"{}\" deny=#true{}",
                escape_kdl_string(&verdict.reason),
                escape_kdl_string(tool_name),
                args_schema_property(discovered, tool_name),
            ));
        }
    }

    // Live tools with findings that cross-validation did not emit.
    for live in discovered {
        if !seen_tools.insert(live.name.clone()) {
            continue;
        }
        let some_findings = findings_map
            .get(&live.name)
            .map(|fs| !fs.is_empty())
            .unwrap_or(false);
        if !some_findings {
            continue;
        }
        let comments = manifest_comment_block(&live.name, &findings_map, &ris_map);
        if tool_has_blocking(&findings_map, &live.name) {
            tools.push(format!(
                "{comments}    tool \"{}\" deny=#true{}",
                escape_kdl_string(&live.name),
                args_schema_property(discovered, &live.name),
            ));
        } else {
            // Findings without a capability verdict — unproven, not
            // proven safe: emit denied so an operator must review the
            // tool before it can be called.
            tools.push(format!(
                "{comments}    // REVIEW: manifest findings without a capability verdict\n    tool \"{}\" deny=#true{}",
                escape_kdl_string(&live.name),
                args_schema_property(discovered, &live.name),
            ));
        }
    }

    if !tools.is_empty() || !discovered.is_empty() || workload.has_content() {
        out.push_str("// === Tools ===\n");
        out.push_str("server \"auto-generated\" {\n");
        emit_workload_hashes(out, workload);
        if !discovered.is_empty() {
            match hash_tools_list(discovered) {
                Ok(digest) => {
                    out.push_str(
                        "    // mcp-guard-tools-list-v4 — re-pin after upgrading from v3\n",
                    );
                    out.push_str(&format!(
                        "    tools-list-hash \"{}\"\n",
                        escape_kdl_string(&digest)
                    ));
                }
                Err(e) => {
                    // Fail visible: the draft must not silently lose its
                    // tools-list pin. The reviewer must fix the offending
                    // field and regenerate.
                    out.push_str(&format!(
                        "    // ERROR: tools-list-hash could not be computed ({})\n",
                        sanitize_for_terminal(&e)
                    ));
                }
            }
        }
        for tool_entry in &tools {
            out.push_str(tool_entry);
            out.push('\n');
        }
        out.push_str("}\n");
    }
}

/// Emit `binary-hash` / `entrypoint-hash` inside the `server` block, before
/// `tools-list-hash`. The hashes pin this host's files, so two REVIEW lines
/// tell the operator to recompute them on the deployment host and to
/// regenerate the draft when the server or its interpreter is updated.
/// A launch target that cannot be bound emits no hash line; its reason is
/// recorded as a comment instead.
fn emit_workload_hashes(out: &mut String, workload: &WorkloadHashes) {
    if workload.binary.is_some() || workload.entrypoint.is_some() {
        out.push_str(
            "    // REVIEW: workload hashes pin this host's files — recompute them on the deployment host\n",
        );
        out.push_str(
            "    // REVIEW: regenerate this draft when the server or its interpreter is updated\n",
        );
        if let Some(ref binary) = workload.binary {
            out.push_str(&format!(
                "    binary-hash \"{}\" target=\"{}\"\n",
                escape_kdl_string(&binary.hash_value),
                escape_kdl_string(&binary.target)
            ));
        }
        if let Some(ref entrypoint) = workload.entrypoint {
            out.push_str(&format!(
                "    entrypoint-hash \"{}\" target=\"{}\"\n",
                escape_kdl_string(&entrypoint.hash_value),
                escape_kdl_string(&entrypoint.target)
            ));
        }
    }
    for reason in &workload.unbound_reasons {
        out.push_str(&format!(
            "    // REVIEW: {}\n",
            sanitize_for_terminal(reason)
        ));
    }
}

/// Determine side_effect value for a tool based on its permissions.
fn determine_side_effect(result: &CrossValidationResult, tool_name: &str) -> &'static str {
    let tool_perms: Vec<&Permission> = result
        .allowed
        .iter()
        .filter(|v| v.tool_name.as_deref() == Some(tool_name))
        .map(|v| &v.permission)
        .collect();

    if tool_perms.contains(&&Permission::ProcessExec) {
        "execute"
    } else if tool_perms.contains(&&Permission::FileWrite) {
        "write"
    } else if tool_perms.contains(&&Permission::NetworkOutbound) {
        "network"
    } else {
        "read_only"
    }
}

/// Build the filesystem sub-section inside defaults.
fn build_fs_section(
    out: &mut String,
    result: &CrossValidationResult,
    capability: &CapabilityProfile,
) {
    out.push_str("    // === Filesystem ===\n");
    out.push_str("    filesystem {\n");
    out.push_str(
        "        // Overlay beats explicit allow. TOCTOU after Auditor check is Warden's job.\n",
    );
    out.push_str("        secret-overlay #true\n");

    for path in &capability.strings.paths {
        if path.starts_with("/usr/lib")
            || path.starts_with("/etc/ssl")
            || path.starts_with("/etc/pki")
            || path.starts_with("/lib")
        {
            let glob = if path.contains('.') {
                path.clone()
            } else {
                format!("{path}/**")
            };
            out.push_str(&format!(
                "        allow \"{}\" mode=\"read\"\n",
                escape_kdl_string(&glob)
            ));
        }
    }

    let has_fs = result
        .allowed
        .iter()
        .any(|v| v.permission == Permission::FileRead || v.permission == Permission::FileWrite);
    if has_fs {
        out.push_str("        // Paths derived from binary string analysis\n");
    }

    out.push_str("    }\n");
}

/// Build the syscalls sub-section inside defaults.
fn build_syscalls_section(
    out: &mut String,
    result: &CrossValidationResult,
    capability: &CapabilityProfile,
) {
    out.push_str("    // === Syscalls ===\n");
    out.push_str("    syscalls {\n");

    // Surface the analysis target so the reviewer knows which syscall table
    // the allow names below were resolved against.
    let t = &capability.analysis.target;
    out.push_str(&format!(
        "        // Target: format={} isa={} abi={} endianness={}\n",
        t.format.as_str(),
        t.isa.as_str(),
        t.abi.as_str(),
        t.endianness.as_str(),
    ));

    // Fail-visible: when syscall analysis did not complete, the allowlist
    // below is built on incomplete data and must be reviewed manually.
    let sc_state = &capability.analysis.syscalls;
    if sc_state.status != crate::inspector::target::AnalysisStatus::Analyzed {
        let reason = sc_state.reason.map(|r| r.as_str()).unwrap_or("none");
        let detail = sc_state
            .detail
            .as_deref()
            .map(|d| format!(" — {}", sanitize_for_terminal(d)))
            .unwrap_or_default();
        out.push_str(&format!(
            "        // REVIEW: syscall analysis status={} reason={}{}\n",
            sc_state.status.as_str(),
            reason,
            detail,
        ));
        out.push_str(
            "        // REVIEW: allowlist below may be incomplete; do not deploy without manual review\n",
        );
    }

    // The `allow` entries below are Linux seccomp names, emitted only
    // for a confirmed Linux ABI. Darwin `x16` values resolve against XNU
    // tables (BSD syscalls and Mach traps in separate namespaces), and an
    // undetermined ABI means the numbering convention itself is unknown —
    // neither may feed a Linux allowlist, so both get review comments.
    if t.abi == crate::inspector::target::SyscallAbi::Linux {
        let mut allowed_set: Vec<&str> = BASE_SYSCALLS.to_vec();

        let blocked_perms: Vec<&Permission> =
            result.blocked.iter().map(|v| &v.permission).collect();

        for sc in &capability.syscalls {
            if let Some(ref name) = sc.syscall_name {
                let name_str = name.as_str();
                if is_syscall_blocked(name_str, &blocked_perms) {
                    continue;
                }
                if !allowed_set.contains(&name_str) {
                    allowed_set.push(name_str);
                }
            }
        }

        // Emit allow lines in groups of ~6 for readability
        for chunk in allowed_set.chunks(6) {
            let args: Vec<String> = chunk
                .iter()
                .map(|s| format!("\"{}\"", escape_kdl_string(s)))
                .collect();
            out.push_str(&format!("        allow {}\n", args.join(" ")));
        }

        // REVIEW comments for blocked syscalls
        for verdict in &result.blocked {
            match verdict.permission {
                Permission::ProcessExec => {
                    for sc in &capability.syscalls {
                        if let Some(ref name) = sc.syscall_name
                            && ["execve", "execveat", "fork", "vfork", "clone", "clone3"]
                                .contains(&name.as_str())
                        {
                            out.push_str(&format!(
                                "        // REVIEW: {} detected in binary but blocked (excess capability)\n",
                                name
                            ));
                        }
                    }
                }
                Permission::NetworkOutbound => {
                    for sc in &capability.syscalls {
                        if let Some(ref name) = sc.syscall_name
                            && ["socket", "connect", "bind", "listen", "accept", "accept4"]
                                .contains(&name.as_str())
                        {
                            out.push_str(&format!(
                                "        // REVIEW: {} detected in binary but blocked (excess capability)\n",
                                name
                            ));
                        }
                    }
                }
                _ => {}
            }
        }
    } else {
        out.push_str(
            "        // REVIEW: target uses a non-Linux syscall ABI — the entries below are\n",
        );
        out.push_str("        // informational only; they are NOT Linux seccomp names and no\n");
        out.push_str("        // `allow` lines were emitted for this target.\n");
        for sc in capability.syscalls.iter().take(40) {
            let num = sc
                .syscall_number
                .map(|n| n.to_string())
                .unwrap_or_else(|| "?".to_string());
            out.push_str(&format!(
                "        //   {} ({}) kind={}\n",
                sanitize_for_terminal(sc.syscall_name.as_deref().unwrap_or("unknown")),
                num,
                sc.kind.as_str(),
            ));
        }
        if capability.syscalls.len() > 40 {
            out.push_str("        //   ... (truncated)\n");
        }
    }

    out.push_str("    }\n");
}

/// Build advisory project hints section from static analysis results.
fn build_project_hints_section(
    out: &mut String,
    hint: &crate::legislator::project_hints::ProjectHint,
) {
    if hint.detected_permissions.is_empty() {
        return;
    }
    out.push_str("\n// === Project Hints (advisory) ===\n");
    out.push_str(&format!(
        "// Project type: {}\n",
        crate::termutil::sanitize_for_terminal(&hint.project_type.to_string())
    ));
    out.push_str(&format!(
        "// Confidence: {}\n",
        crate::termutil::sanitize_for_terminal(hint.confidence_summary.as_str())
    ));
    for h in &hint.detected_permissions {
        out.push_str(&format!(
            "// Hint: {} ({}, {}) — {}\n",
            crate::termutil::sanitize_for_terminal(h.permission.as_str()),
            crate::termutil::sanitize_for_terminal(h.confidence.as_str()),
            crate::termutil::sanitize_for_terminal(&h.source.to_string()),
            crate::termutil::sanitize_for_terminal(&h.evidence)
        ));
    }
}

/// Check if a syscall name corresponds to any blocked permission category.
fn is_syscall_blocked(name: &str, blocked_perms: &[&Permission]) -> bool {
    if blocked_perms.contains(&&Permission::ProcessExec)
        && ["execve", "execveat", "fork", "vfork", "clone", "clone3"].contains(&name)
    {
        return true;
    }
    if blocked_perms.contains(&&Permission::NetworkOutbound)
        && [
            "socket",
            "connect",
            "bind",
            "listen",
            "accept",
            "accept4",
            "sendto",
            "recvfrom",
            "sendmsg",
            "recvmsg",
            "shutdown",
            "setsockopt",
            "getsockopt",
            "socketpair",
        ]
        .contains(&name)
    {
        return true;
    }
    false
}

#[cfg(test)]
mod tests;
